### ISSUE TITLE
Add website link to repo?

### ISSUE THREAD

**Issue by Pustur** [Spyridox/USIGeek#2]
Can you add the website link next to the repo description? That would be convenient 👌

**Comment by Pustur** [comment]
@LambdaFalcon I think you missed this issue, even I forgot about it 😄
Feel free to close it when you have time.

**Comment by aronfiechter** [comment]
Oh, yeah you're right!
However, this repo is not really being used anymore, I'm gonna see this summer if we still need it.

**Comment by Pustur** [comment]
I'm trying to clean up my open issues, so I'm closing this as well
